### ISSUE TITLE
PEEK abbreviation

### ISSUE THREAD

**Issue by ukcroupier** [dmsc/fastbasic#15]
Any chance of an abbreviation for PEEK?

I use peek a lot, especially in my 10 liners, so even a single characters saved would be useful.

PE.
PK.
or even the less intuitive K. for a 2 character saving.

**Comment by dmsc** [comment]
Hi!

> Any chance of an abbreviation for PEEK?
> 
> I use peek a lot, especially in my 10 liners, so even a single characters saved would be useful.
> 
> PE.
> PK.
> or even the less intuitive K. for a 2 character saving.

I did not add abbreviations to functions because that differs with the way Atari BASIC works.

FastBasic work the same as Atari BASIC, abbreviations skip the remaining part of a word after a dot, so a possible abbreviation would be "P.(" for PEEK, "D.(" for DPEEK, "PA.(" for paddle, "PT.(" for PTRIG, "ST.(" for STICK, "STR.(" for STRIG, "PM.(" for PMADR, "R.(" for RAND.

IMHO, you could build a list of possible abbreviations and post it to AtariAge, so more people can comment.
