### ISSUE TITLE
how do i load and save to a virtual disk?

### ISSUE THREAD

**Issue by drarem** [dmsc/fastbasic#36]
I tried creating a disk using mydos 3.01 and dos 2.5, then accessing it trying to save or load such as d2:..  from fb 4.4 i get error 140. What is wrong?

**Comment by dmsc** [comment]
Hi!

Just seeing this, I have been really busy.

Error 140 is "framing error", means that the serial connection to your disk drive is not ok, and it is really hard to see. I suspect that you are instead getting error **148**, "Bad disk format".

In that case, this is because you are trying to save to a DOS-2.5 or MyDOS formatted disk from BW-DOS, and those DOS are incompatible, so you can't write to it - BW-DOS uses the SpartaDOS disk format.

So, you are probably asking: How I move a file from a BW-DOS formatted disk to a MyDOS or DOS-2.5 formatted disk?

There are multiple possibilities, perhaps easier (when using a real Atari) is to use a full BW-DOS disk - you can download BW130A.ATR from here: http://ftp.pigwa.net/stuff/collections/nir_dary_cds/DOS/BW%20DOS%201.30/

Booting the BW-DOS disk, there is a "MENU" program that can read and write DOS-2.5 formatted disks, use this to copy files.

Have Fun!

**Comment by dmsc** [comment]
Closing, as there were no further replies.

**Comment by drarem** [comment]
Many thanks. Great program.
