### ISSUE TITLE
Add joystick support to the IDE

### ISSUE THREAD

**Issue by eahumada** [dmsc/fastbasic#43]
The joystick is the pointing device by excellence for Atari, could be great is there is some way in that the joystick could used to navigate across the sources in the editor.

It will allow to review the sources with jsA8E emulator that not have support for keyboard arrows: https://eahumada.github.io/AtariOnline/fastbasic.html?disk_filename=fastbasic.atr

**Comment by dmsc** [comment]
Hi!

> The joystick is the pointing device by excellence for Atari, could be great is there is some way in that the joystick could used to navigate across the sources in the editor.
>

The problem is, adding support for proper joystick movement would add a fair amount of code to the IDE, and IMHO, using a joystick for text movement is not very pleasant :)

I will keep this open, but don't plan to implement it anytime soon.

 
> It will allow to review the sources with jsA8E emulator that not have support for keyboard arrows: https://eahumada.github.io/AtariOnline/fastbasic.html?disk_filename=fastbasic.atr

Strange emulator. It outputs a "CONTROL-L" character each time I press the control key, and "L" on pressing of F1, so i makes the IDE very hard to use!

IMHO, it would be better to fix the emulator, adding support for activating/deactivating cursor keys. Note that the IDE also supports page-up and page-down keys on the Atari800 emulator, mapped to the 1200XL function keys.

Have Fun!

**Comment by eahumada** [comment]
Yes, you are right, makes sense. By the way, the emulator is a work in progress may be I switch to JS mame or other JavaScript emulator if I found one, but at least you can run the demos live online (ej. JOYAS.COM), review the code (TYPE PI.BAS) and test the compiler. I get the idea a couple of days ago.

https://eahumada.github.io/AtariOnline/
